import { Router } from 'express';
import { prisma } from '../db';
import { AuthenticatedRequest } from '../middleware/auth';
import { executeAIRequest } from '../services/aiEngine';
import { aiQueueManager } from '../services/aiQueueManager';

const router = Router();

// Helper: decodifica headers que chegam em Base64 do frontend
const decodeHeader = (val: string | string[] | undefined): string => {
  if (!val) return '';
  const str = Array.isArray(val) ? val[0] : val;
  if (!str) return '';
  try { return decodeURIComponent(escape(atob(str))); } catch { return str; }
};

export const projectJobsQueue: Record<string, any> = new Proxy({}, {
  get(target, prop: string) {
    if (typeof prop !== 'string') return undefined;
    const activeJob = aiQueueManager.getActiveJob(prop);
    if (activeJob) {
      return {
        status: activeJob.status,
        currentModel: activeJob.currentModel,
        error: activeJob.error
      };
    }
    const queue = aiQueueManager.getQueueList(prop);
    if (queue.length > 0) {
      const last = queue[queue.length - 1];
      return {
        status: last.status,
        currentModel: last.currentModel,
        error: last.error
      };
    }
    return undefined;
  },
  set(target, prop: string, value: any) {
    if (typeof prop === 'string' && value && value.status === 'cancelled') {
      const activeJob = aiQueueManager.getActiveJob(prop);
      if (activeJob) {
        aiQueueManager.cancelItem(prop, activeJob.id);
      }
    }
    return true;
  }
});

// Background task worker method
async function processAIProjectGeneration(
  projectId: string, 
  prompt: string, 
  customApiKey?: string, 
  customModel?: string, 
  registeredModels?: string[],
  customProxyUrl?: string,
  customSkills?: any[], 
  aiProvider?: string, 
  ollamaEndpoint?: string,
  lowSpecMode?: boolean
) {
  projectJobsQueue[projectId] = { status: 'processing' };
  try {
    const page = await prisma.page.findFirst({
      where: { projectId, isHomepage: true }
    });

    if (!page) throw new Error("Homepage page not found in project");

    // Invoke AI with dynamic attempt updates and proxy
    const response = await executeAIRequest(
      prompt,
      { html: page.html, css: page.css, js: page.js },
      {
        provider: (aiProvider as any) || 'gemini',
        apiKey: customApiKey,
        model: customModel,
        registeredModels: registeredModels,
        proxyUrl: customProxyUrl,
        ollamaEndpoint: ollamaEndpoint,
        lowSpecMode: lowSpecMode,
        customSkills: customSkills,
        onProgress: (info) => {
          projectJobsQueue[projectId] = {
            status: 'processing',
            currentModel: info.model,
            attempt: 1,
            total: 1
          };
        }
      }
    );

    // Save final generated code to database
    await prisma.page.update({
      where: { id: page.id },
      data: {
        html: response.html || page.html,
        css: response.css || page.css,
        js: response.js || page.js
      }
    });

    // Mirror to version snapshot
    await prisma.version.create({
      data: {
        name: "AI Initial Setup",
        description: `Autogenerated mockup: ${prompt}`,
        projectId,
        snapshot: {
          pages: [
            {
              id: page.id,
              name: page.name,
              slug: page.slug,
              html: response.html || page.html,
              css: response.css || page.css,
              js: response.js || page.js
            }
          ]
        }
      }
    });

    projectJobsQueue[projectId] = { status: 'completed' };
  } catch (err: any) {
    console.error("AI Generation job worker error for project " + projectId + ":", err);
    projectJobsQueue[projectId] = { status: 'failed', error: err.message };
  }
}

// Check job task status endpoint
router.get('/jobs/:projectId/status', async (req: AuthenticatedRequest, res: any) => {
  const projectId = req.params.projectId as string;
  const activeAiQueueJob = aiQueueManager.getActiveJob(projectId);
  if (activeAiQueueJob) {
    return res.json({
      status: activeAiQueueJob.status,
      currentModel: activeAiQueueJob.currentModel,
      attempt: 1,
      total: 1,
      type: activeAiQueueJob.type,
      error: activeAiQueueJob.error
    });
  }
  const job = projectJobsQueue[projectId] || { status: 'completed' };
  return res.json(job);
});

// List all active jobs
router.get('/jobs', async (req: AuthenticatedRequest, res: any) => {
  return res.json(projectJobsQueue);
});

// Cancel Job (alias via /jobs/:projectId/cancel)
router.post('/jobs/:projectId/cancel', async (req: AuthenticatedRequest, res: any) => {
  const projectId = req.params.projectId as string;
  const activeJob = aiQueueManager.getActiveJob(projectId);
  if (activeJob) {
    aiQueueManager.cancelItem(projectId, activeJob.id);
  }
  return res.json({ message: 'Job cancelled successfully' });
});

// List Projects
router.get('/', async (req: AuthenticatedRequest, res: any) => {
  try {
    const userId = req.userId as string;
    const projects = await prisma.project.findMany({
      where: {
        members: {
          some: {
            userId
          }
        }
      },
      include: {
        pages: {
          select: {
            id: true
          }
        }
      }
    });

    const enrichedProjects = projects.map(p => {
      const activeJob = aiQueueManager.getActiveJob(p.id);
      return {
        ...p,
        aiJob: (activeJob && (activeJob.status === 'pending' || activeJob.status === 'processing')) ? activeJob : null
      };
    });

    return res.json(enrichedProjects);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

import { processWebsiteRemasterJob } from '../services/siteRemaster';
import { templates } from '../data/templates';

// Create Project
router.post('/', async (req: AuthenticatedRequest, res: any) => {
  try {
    const {
      name,
      description,
      isAIPrompt,
      templateType,
      remasterWebsiteUrl,
      leadId,
      pagesToGenerate,
      siteStyle,
      segment,
      colorPalette,
      businessName
    } = req.body;
    if (!name) {
      return res.status(400).json({ error: 'Project name is required' });
    }

    const userId = req.userId as string;
    
    let initialHtml = `<div class="min-h-screen bg-slate-900 text-white flex flex-col justify-center items-center">
  <h1 class="text-4xl font-bold mb-4">Gerando site profissional...</h1>
  <p class="text-slate-400">Por favor, aguarde alguns instantes enquanto a IA constrói o mockup completo.</p>
</div>`;
    let initialCss = 'body { margin: 0; font-family: sans-serif; }';
    let initialJs = '';

    if (templateType && templates[templateType as keyof typeof templates]) {
      const template = templates[templateType as keyof typeof templates];
      initialHtml = template.html;
      initialCss = template.css;
      initialJs = template.js;
    } else if (!isAIPrompt && !remasterWebsiteUrl) {
      initialHtml = `<div class="min-h-screen bg-white text-slate-900 flex flex-col justify-center items-center">
  <h1 class="text-4xl font-bold mb-4">Bem-vindo ao ${name}</h1>
  <p class="text-slate-500">Comece a editar o seu site adicionando novos elementos.</p>
</div>`;
    }

    // Preparar lista de páginas iniciais
    let pagesCreateData: any[] = [];
    if (Array.isArray(pagesToGenerate) && pagesToGenerate.length > 0) {
      pagesCreateData = pagesToGenerate.map((p: any, idx: number) => {
        const isHome = !!p.isHomepage || p.slug === 'index' || idx === 0;
        const pageName = p.name || (isHome ? 'Home' : `Página ${idx + 1}`);
        const pageSlug = p.slug || (isHome ? 'index' : (p.name ? p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') : `pagina-${idx + 1}`));
        return {
          name: pageName,
          slug: pageSlug,
          title: pageName,
          isHomepage: isHome,
          html: initialHtml,
          css: initialCss,
          js: initialJs
        };
      });
    } else {
      pagesCreateData = [{
        name: 'Home',
        slug: 'index',
        title: 'Home',
        isHomepage: true,
        html: initialHtml,
        css: initialCss,
        js: initialJs
      }];
    }

    const project = await prisma.project.create({
      data: {
        name,
        description,
        members: {
          create: {
            userId,
            role: 'OWNER'
          }
        },
        pages: {
          create: pagesCreateData
        }
      },
      include: {
        pages: true
      }
    });

    // Se um leadId foi fornecido, vincula o projeto diretamente ao lead no CRM com segurança via Prisma Client
    if (leadId) {
      try {
        const existingLead = await prisma.lead.findUnique({ where: { id: leadId } });
        if (existingLead && existingLead.userId === userId) {
          await prisma.lead.update({
            where: { id: leadId },
            data: { projectId: project.id }
          });
        }
      } catch (leadLinkErr) {
        // Silently ignore if lead not found or other minor issues
      }
    }

    // Busca configurações salvas no banco de dados do usuário como fallback prioritário via Prisma Client
    let dbGeminiKey: string | undefined;
    let dbProxyUrl: string | undefined;
    let dbCustomModels: string[] | undefined;
    let dbCustomSkills: any[] | undefined;

    try {
      const userSettings = await prisma.user.findUnique({
        where: { id: userId },
        select: {
          geminiApiKey: true,
          aiProxyUrl: true,
          customAiModels: true,
          customAiSkills: true,
        }
      });

      if (userSettings) {
        dbGeminiKey = userSettings.geminiApiKey || undefined;
        dbProxyUrl = userSettings.aiProxyUrl || undefined;
        if (userSettings.customAiModels) {
          const parsedModels = typeof userSettings.customAiModels === 'string' ? JSON.parse(userSettings.customAiModels) : userSettings.customAiModels;
          if (Array.isArray(parsedModels)) {
            dbCustomModels = (parsedModels as any[]).map(m => typeof m === 'string' ? m : m.id);
          }
        }
        if (userSettings.customAiSkills) {
          const parsedSkills = typeof userSettings.customAiSkills === 'string' ? JSON.parse(userSettings.customAiSkills) : userSettings.customAiSkills;
          if (Array.isArray(parsedSkills)) {
            dbCustomSkills = parsedSkills as any[];
          }
        }
      }
    } catch (e) {
      console.warn('Falha ao buscar configurações do usuário no banco:', e);
    }

    const clientGeminiKey = decodeHeader(req.headers['x-gemini-key'] || req.headers['X-Gemini-Key']) || dbGeminiKey || process.env.GEMINI_API_KEY;
    const clientProxyUrl = decodeHeader(req.headers['x-proxy-url'] || req.headers['X-Proxy-Url']) || dbProxyUrl || process.env.AI_PROXY_URL;
    let registeredModels: string[] | undefined = dbCustomModels;
    try {
      const rawModels = decodeHeader(req.headers['x-gemini-models'] || req.headers['X-Gemini-Models']);
      if (rawModels) registeredModels = JSON.parse(rawModels);
    } catch {}

    let customSkills: any[] | undefined = dbCustomSkills;
    try {
      const rawSkills = decodeHeader(req.headers['x-ai-skills'] || req.headers['X-Ai-Skills'] || req.headers['X-AI-Skills']);
      if (rawSkills) customSkills = JSON.parse(rawSkills);
    } catch {}

    const aiProvider = decodeHeader(req.headers['x-ai-provider'] || req.headers['X-Ai-Provider'] || req.headers['X-AI-Provider']);
    const customModel = decodeHeader(req.headers['x-ai-model'] || req.headers['X-Ai-Model'] || req.headers['X-AI-Model'] || req.headers['x-ollama-model'] || req.headers['X-Ollama-Model']);
    const ollamaEndpoint = decodeHeader(req.headers['x-ollama-endpoint'] || req.headers['X-Ollama-Endpoint']);
    const lowSpecMode = (req.headers['x-ollama-low-spec'] || req.headers['X-Ollama-Low-Spec']) ? (req.headers['x-ollama-low-spec'] || req.headers['X-Ollama-Low-Spec']) === 'true' : undefined;

    // 1. Caso seja remasterização/melhoria de site existente (analisa páginas e subpáginas)
    if (remasterWebsiteUrl) {
      aiQueueManager.enqueue(
        project.id,
        'site_remaster',
        `Remasterizar site: ${remasterWebsiteUrl}`,
        undefined,
        {
          remasterWebsiteUrl,
          businessName: name,
          customApiKey: clientGeminiKey,
          registeredModels,
          customProxyUrl: clientProxyUrl,
          customSkills,
          aiProvider,
          ollamaEndpoint,
          customModel,
          lowSpecMode,
          userId
        }
      );
    } 
    // 2. Geração normal com IA a partir de prompt
    else if (isAIPrompt || description?.includes('Segmento:') || (Array.isArray(pagesToGenerate) && pagesToGenerate.length > 0)) {
      const targetBusinessName = (businessName || name || '').trim();
      const pagesCount = Array.isArray(pagesToGenerate) && pagesToGenerate.length > 0 ? pagesToGenerate.length : 1;
      const pagesNames = Array.isArray(pagesToGenerate) && pagesToGenerate.length > 0 ? pagesToGenerate.map((p: any) => p.name).join(', ') : 'Home';
      
      const aiPromptMessage = `Gere um website completo, espetacular e ultra profissional de ${pagesCount} página(s) (${pagesNames}) para a empresa "${targetBusinessName}".
Segmento: ${segment || 'Geral'}.
Estilo Visual: ${siteStyle || 'Moderno'}.
Paleta de Cores: ${colorPalette || 'Elegante'}.
Descrição e Objetivos: ${description || 'Site institucional de alta conversão'}.`;
      
      aiQueueManager.enqueue(
        project.id,
        'site_generation',
        aiPromptMessage,
        undefined,
        {
          customApiKey: clientGeminiKey,
          customModel,
          registeredModels,
          customProxyUrl: clientProxyUrl,
          customSkills,
          aiProvider,
          ollamaEndpoint,
          lowSpecMode,
          pagesToGenerate,
          businessName: targetBusinessName,
          segment,
          visualStyle: siteStyle,
          colorPalette
        }
      );
    }

    return res.status(201).json(project);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

// Cancel Job
router.post('/:id/cancel', async (req: AuthenticatedRequest, res: any) => {
  const projectId = req.params.id as string;
  if (projectJobsQueue[projectId]) {
    projectJobsQueue[projectId].status = 'cancelled';
  }
  return res.json({ message: 'Job cancelled successfully' });
});

// Regenerate site with AI using project and lead information
router.post('/:id/regenerate', async (req: AuthenticatedRequest, res: any) => {
  try {
    const userId = req.userId as string;
    const projectId = req.params.id as string;

    const project = await prisma.project.findFirst({
      where: {
        id: projectId,
        members: { some: { userId } }
      },
      include: {
        pages: true,
        leads: true
      }
    });

    if (!project) {
      return res.status(404).json({ error: 'Projeto não encontrado' });
    }

    const attachedLead = project.leads && project.leads.length > 0 ? project.leads[0] : null;

    let dbGeminiKey: string | undefined;
    let dbProxyUrl: string | undefined;
    let dbCustomModels: string[] | undefined;
    let dbCustomSkills: any[] | undefined;

    try {
      const userSettings = await prisma.user.findUnique({
        where: { id: userId },
        select: {
          geminiApiKey: true,
          aiProxyUrl: true,
          customAiModels: true,
          customAiSkills: true,
        }
      });

      if (userSettings) {
        dbGeminiKey = userSettings.geminiApiKey || undefined;
        dbProxyUrl = userSettings.aiProxyUrl || undefined;
        if (userSettings.customAiModels) {
          const parsedModels = typeof userSettings.customAiModels === 'string' ? JSON.parse(userSettings.customAiModels) : userSettings.customAiModels;
          if (Array.isArray(parsedModels)) {
            dbCustomModels = (parsedModels as any[]).map(m => typeof m === 'string' ? m : m.id);
          }
        }
        if (userSettings.customAiSkills) {
          const parsedSkills = typeof userSettings.customAiSkills === 'string' ? JSON.parse(userSettings.customAiSkills) : userSettings.customAiSkills;
          if (Array.isArray(parsedSkills)) {
            dbCustomSkills = parsedSkills as any[];
          }
        }
      }
    } catch {}

    const clientGeminiKey = decodeHeader(req.headers['x-gemini-key'] || req.headers['X-Gemini-Key']) || dbGeminiKey || process.env.GEMINI_API_KEY;
    const clientProxyUrl = decodeHeader(req.headers['x-proxy-url'] || req.headers['X-Proxy-Url']) || dbProxyUrl || process.env.AI_PROXY_URL;
    let registeredModels: string[] | undefined = dbCustomModels;
    try {
      const rawModels = decodeHeader(req.headers['x-gemini-models'] || req.headers['X-Gemini-Models']);
      if (rawModels) registeredModels = JSON.parse(rawModels);
    } catch {}

    let customSkills: any[] | undefined = dbCustomSkills;
    try {
      const rawSkills = decodeHeader(req.headers['x-ai-skills'] || req.headers['X-Ai-Skills'] || req.headers['X-AI-Skills']);
      if (rawSkills) customSkills = JSON.parse(rawSkills);
    } catch {}

    const aiProvider = decodeHeader(req.headers['x-ai-provider'] || req.headers['X-Ai-Provider'] || req.headers['X-AI-Provider']);
    const customModel = decodeHeader(req.headers['x-ai-model'] || req.headers['X-Ai-Model'] || req.headers['X-AI-Model'] || req.headers['x-ollama-model'] || req.headers['X-Ollama-Model']);
    const ollamaEndpoint = decodeHeader(req.headers['x-ollama-endpoint'] || req.headers['X-Ollama-Endpoint']);
    const lowSpecMode = (req.headers['x-ollama-low-spec'] || req.headers['X-Ollama-Low-Spec']) ? (req.headers['x-ollama-low-spec'] || req.headers['X-Ollama-Low-Spec']) === 'true' : undefined;

    const targetBusinessName = attachedLead?.name || project.name;
    const segment = attachedLead?.company || 'Comércio e Serviços';
    const description = project.description || 'Site institucional de alta conversão';

    const aiPromptMessage = `Gere um website completo, espetacular e ultra profissional de 4 páginas (Home, Sobre, Serviços, Contato) para a empresa "${targetBusinessName}".
Segmento: ${segment}.
Informações do Cliente: Telefone: ${attachedLead?.phone || 'N/A'}, Email: ${attachedLead?.email || 'N/A'}, Endereço: ${attachedLead?.address || 'N/A'}.
Descrição e Objetivos: ${description}.`;

    const pagesToGenerate = project.pages.map(p => ({
      name: p.name,
      slug: p.slug,
      isHomepage: p.isHomepage
    }));

    aiQueueManager.enqueue(
      project.id,
      'site_generation',
      aiPromptMessage,
      undefined,
      {
        customApiKey: clientGeminiKey,
        customModel,
        registeredModels,
        customProxyUrl: clientProxyUrl,
        customSkills,
        aiProvider,
        ollamaEndpoint,
        lowSpecMode,
        pagesToGenerate,
        businessName: targetBusinessName,
        segment,
        visualStyle: 'Moderno & Profissional',
        colorPalette: 'Dark Luxury / Tech'
      }
    );

    return res.json({ message: 'Regeração iniciada com sucesso', project });
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

// List all active jobs
router.get('/jobs', async (req: AuthenticatedRequest, res: any) => {
  return res.json(projectJobsQueue);
});

// Get Project Details & Pages
router.get('/:id', async (req: AuthenticatedRequest, res: any) => {
  try {
    const userId = req.userId as string;
    const id = req.params.id as string;
    const project = await prisma.project.findFirst({
      where: {
        id,
        members: {
          some: {
            userId
          }
        }
      },
      include: {
        pages: true,
        assets: true
      }
    });

    if (!project) {
      return res.status(404).json({ error: 'Project not found' });
    }

    return res.json(project);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

// Update Project Info (Nome, Descrição, Status, Domínio)
router.put('/:id', async (req: AuthenticatedRequest, res: any) => {
  try {
    const id = req.params.id as string;
    const userId = req.userId as string;
    const { name, description, status, domain, favicon } = req.body;

    const membership = await prisma.projectMember.findFirst({
      where: {
        projectId: id,
        userId: userId
      }
    });

    if (!membership) {
      return res.status(403).json({ error: 'Você não tem permissão para editar este projeto' });
    }

    const updated = await prisma.project.update({
      where: { id },
      data: {
        ...(name !== undefined && { name: name.trim() }),
        ...(description !== undefined && { description: description?.trim() || null }),
        ...(status !== undefined && { status }),
        ...(domain !== undefined && { domain: domain?.trim() || null }),
        ...(favicon !== undefined && { favicon })
      },
      include: {
        pages: {
          select: { id: true, name: true, slug: true, isHomepage: true }
        }
      }
    });

    return res.json(updated);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

// Delete Project
router.delete('/:id', async (req: AuthenticatedRequest, res: any) => {
  try {
    const id = req.params.id as string;
    const userId = req.userId as string;

    const project = await prisma.project.findUnique({
      where: { id }
    });

    if (!project) {
      return res.status(404).json({ error: 'Projeto não encontrado' });
    }

    // Verifica membros
    const members = await prisma.projectMember.findMany({
      where: { projectId: id }
    });

    if (members && members.length > 0) {
      const isMember = members.some(m => m.userId === userId);
      if (!isMember) {
        return res.status(403).json({ error: 'Você não tem permissão para excluir este projeto' });
      }
    }

    // Cancela jobs de IA ativos na fila para este projeto
    if (projectJobsQueue[id]) {
      delete projectJobsQueue[id];
    }

    // Exclusão explícita de dependências para evitar violações de chave estrangeira (FK)
    try {
      await prisma.page.deleteMany({ where: { projectId: id } });
    } catch (e) {
      console.warn('[Delete Project] Erro ao deletar páginas:', e);
    }

    try {
      await prisma.projectMember.deleteMany({ where: { projectId: id } });
    } catch (e) {
      console.warn('[Delete Project] Erro ao deletar membros do projeto:', e);
    }

    try {
      await prisma.version.deleteMany({ where: { projectId: id } });
    } catch (e) {
      console.warn('[Delete Project] Erro ao deletar versões:', e);
    }

    try {
      await prisma.asset.deleteMany({ where: { projectId: id } });
    } catch (e) {
      console.warn('[Delete Project] Erro ao deletar assets:', e);
    }
    
    // Desvincula leads no CRM vinculados ao projeto de forma segura com Prisma
    try {
      await prisma.lead.updateMany({
        where: { projectId: id },
        data: { projectId: null }
      });
    } catch (e) {
      console.warn('[Delete Project] Erro ao desvincular leads:', e);
    }

    await prisma.project.delete({ where: { id } });
    return res.json({ message: 'Projeto excluído com sucesso' });
  } catch (error: any) {
    console.error('Erro ao deletar projeto:', error);
    return res.status(500).json({ error: error.message || 'Falha ao excluir projeto' });
  }
});

// Import Project from ZIP (Base64)
router.post('/import-zip', async (req: AuthenticatedRequest, res: any) => {
  try {
    const { name, description, zipBase64, targetProjectId } = req.body;
    const userId = req.userId as string;

    if (!zipBase64) {
      return res.status(400).json({ error: 'Arquivo ZIP em Base64 é obrigatório.' });
    }

    const JSZip = (await import('jszip')).default;
    const zipData = Buffer.from(zipBase64.replace(/^data:.*?;base64,/, ''), 'base64');
    const zip = await JSZip.loadAsync(zipData);

    const extractedPages: Array<{
      name: string;
      slug: string;
      title: string;
      seoTitle?: string;
      seoDescription?: string;
      isHomepage: boolean;
      html: string;
      css: string;
      js: string;
    }> = [];

    const files = Object.keys(zip.files);
    const htmlFiles = files.filter(f => !zip.files[f].dir && f.endsWith('.html') && !f.startsWith('__MACOSX/'));

    if (htmlFiles.length === 0) {
      return res.status(400).json({ error: 'Nenhum arquivo HTML encontrado no arquivo ZIP.' });
    }

    for (const filePath of htmlFiles) {
      const rawHtml = await zip.file(filePath)!.async('string');
      const basename = filePath.split('/').pop()!.replace(/\.html$/, '');
      const isHome = basename === 'index' || basename === 'home' || filePath === 'index.html';
      const slug = isHome ? 'index' : basename.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      const nameTitle = isHome ? 'Home' : basename.charAt(0).toUpperCase() + basename.slice(1);

      // Tenta extrair <title> e <meta name="description">
      const titleMatch = rawHtml.match(/<title[^>]*>([^<]+)<\/title>/i);
      const title = titleMatch ? titleMatch[1].trim() : nameTitle;

      const descMatch = rawHtml.match(/<meta\s+name=["']description["']\s+content=["']([^"']+)["'][^>]*>/i) ||
                        rawHtml.match(/<meta\s+content=["']([^"']+)["']\s+name=["']description["'][^>]*>/i);
      const seoDescription = descMatch ? descMatch[1].trim() : '';

      // Extrai corpo ou <div id="canvas-root"> ou <body>
      let bodyHtml = rawHtml;
      const bodyMatch = rawHtml.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
      if (bodyMatch) {
        bodyHtml = bodyMatch[1].trim();
      }

      // Procura arquivo CSS correspondente no ZIP
      let cssContent = '';
      const possibleCssFiles = [`css/${slug}.css`, `${slug}.css`, `css/style.css`, `style.css`];
      for (const cssPath of possibleCssFiles) {
        const found = zip.file(cssPath);
        if (found) {
          cssContent = await found.async('string');
          break;
        }
      }

      // Procura arquivo JS correspondente no ZIP
      let jsContent = '';
      const possibleJsFiles = [`js/${slug}.js`, `${slug}.js`, `js/script.js`, `script.js`];
      for (const jsPath of possibleJsFiles) {
        const found = zip.file(jsPath);
        if (found) {
          jsContent = await found.async('string');
          break;
        }
      }

      extractedPages.push({
        name: nameTitle,
        slug,
        title,
        seoTitle: title,
        seoDescription,
        isHomepage: isHome,
        html: bodyHtml,
        css: cssContent,
        js: jsContent
      });
    }

    // Garante que exista pelo menos uma Home
    if (!extractedPages.some(p => p.isHomepage) && extractedPages.length > 0) {
      extractedPages[0].isHomepage = true;
      extractedPages[0].slug = 'index';
    }

    let finalProject: any;

    if (targetProjectId) {
      // Importar / Mesclar em projeto existente
      const existing = await prisma.project.findFirst({
        where: { id: targetProjectId, members: { some: { userId } } }
      });
      if (!existing) return res.status(404).json({ error: 'Projeto alvo não encontrado.' });

      for (const ep of extractedPages) {
        const existingPage = await prisma.page.findFirst({
          where: { projectId: targetProjectId, slug: ep.slug }
        });

        if (existingPage) {
          await prisma.page.update({
            where: { id: existingPage.id },
            data: {
              name: ep.name,
              title: ep.title,
              seoTitle: ep.seoTitle,
              seoDescription: ep.seoDescription,
              html: ep.html,
              css: ep.css || existingPage.css,
              js: ep.js || existingPage.js
            }
          });
        } else {
          await prisma.page.create({
            data: {
              projectId: targetProjectId,
              name: ep.name,
              slug: ep.slug,
              title: ep.title,
              seoTitle: ep.seoTitle,
              seoDescription: ep.seoDescription,
              isHomepage: ep.isHomepage,
              html: ep.html,
              css: ep.css,
              js: ep.js
            }
          });
        }
      }

      finalProject = await prisma.project.findUnique({
        where: { id: targetProjectId },
        include: { pages: true }
      });
    } else {
      // Criar novo projeto a partir do ZIP
      const projectName = name || 'Site Importado (ZIP)';
      finalProject = await prisma.project.create({
        data: {
          name: projectName,
          description: description || `Projeto importado via arquivo ZIP com ${extractedPages.length} página(s).`,
          members: {
            create: {
              userId,
              role: 'OWNER'
            }
          },
          pages: {
            create: extractedPages.map(p => ({
              name: p.name,
              slug: p.slug,
              title: p.title,
              seoTitle: p.seoTitle,
              seoDescription: p.seoDescription,
              isHomepage: p.isHomepage,
              html: p.html,
              css: p.css,
              js: p.js
            }))
          }
        },
        include: {
          pages: true
        }
      });
    }

    return res.status(201).json(finalProject);
  } catch (error: any) {
    console.error('Erro ao importar projeto ZIP:', error);
    return res.status(500).json({ error: error.message || 'Falha ao processar arquivo ZIP.' });
  }
});

export const projectRouter = router;
