import { Router } from 'express';
import { prisma } from '../db';
import { AuthenticatedRequest } from '../middleware/auth';
import { uploadProjectToFTP } from '../services/ftp';
import { generateAIResponse } from '../services/gemini';
import { extractNavbarAndFooter } from '../services/siteRemaster';
import fs from 'fs';
import path from 'path';

const router = Router();

// Helper: decodifica headers que chegam em Base64 do frontend
const decodeHeader = (val: string | string[] | undefined): string => {
  if (!val) return '';
  const str = Array.isArray(val) ? val[0] : val;
  if (!str) return '';
  try { return decodeURIComponent(escape(atob(str))); } catch { return str; }
};

export const projectJobsQueue: Record<string, { 
  status: 'pending' | 'processing' | 'completed' | 'failed'; 
  currentModel?: string;
  attempt?: number;
  total?: number;
  error?: string;
}> = {};

// Background task worker method
async function processAIProjectGeneration(
  projectId: string, 
  prompt: string, 
  customApiKey?: string, 
  customModel?: string, 
  registeredModels?: string[],
  customProxyUrl?: string,
  customSkills?: any[]
) {
  projectJobsQueue[projectId] = { status: 'processing' };
  try {
    const page = await prisma.page.findFirst({
      where: { projectId, isHomepage: true }
    });

    if (!page) throw new Error("Homepage page not found in project");

    // Invoke Gemini with dynamic attempt updates and proxy
    const response = await generateAIResponse(
      prompt,
      { html: page.html, css: page.css, js: page.js },
      customApiKey,
      customModel,
      registeredModels,
      (model, attempt, total) => {
        projectJobsQueue[projectId] = {
          status: 'processing',
          currentModel: model,
          attempt,
          total
        };
      },
      customProxyUrl,
      customSkills
    );

    // Save final generated code to database
    const finalHtml = response.html || page.html;
    await prisma.page.update({
      where: { id: page.id },
      data: {
        html: finalHtml,
        css: response.css || page.css,
        js: response.js || page.js
      }
    });

    // Extrai e persiste globals no projeto
    const { navbarHtml, footerHtml } = extractNavbarAndFooter(finalHtml);
    if (navbarHtml || footerHtml) {
      await prisma.project.update({
        where: { id: projectId },
        data: {
          ...(navbarHtml ? { navbarHtml } : {}),
          ...(footerHtml ? { footerHtml } : {})
        }
      }).catch(e => console.warn('Falha ao salvar globals no projeto:', e));
    }

    // Mirror to version snapshot
    await prisma.version.create({
      data: {
        name: "AI Initial Setup",
        description: `Autogenerated mockup: ${prompt}`,
        projectId,
        snapshot: {
          pages: [
            {
              id: page.id,
              name: page.name,
              slug: page.slug,
              html: response.html || page.html,
              css: response.css || page.css,
              js: response.js || page.js
            }
          ]
        }
      }
    });

    projectJobsQueue[projectId] = { status: 'completed' };
  } catch (err: any) {
    console.error("AI Generation job worker error for project " + projectId + ":", err);
    projectJobsQueue[projectId] = { status: 'failed', error: err.message };
  }
}

// Check job task status endpoint
router.get('/jobs/:projectId/status', async (req: AuthenticatedRequest, res: any) => {
  const projectId = req.params.projectId as string;
  const job = projectJobsQueue[projectId] || { status: 'completed' }; // fallback default to completed if no active job queue exists
  return res.json(job);
});

// List Projects
router.get('/', async (req: AuthenticatedRequest, res: any) => {
  try {
    const userId = req.userId as string;
    const projects = await prisma.project.findMany({
      where: {
        members: {
          some: {
            userId
          }
        }
      },
      include: {
        pages: {
          select: {
            id: true
          }
        }
      }
    });
    return res.json(projects);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

import { processWebsiteRemasterJob } from '../services/siteRemaster';

// Create Project
router.post('/', async (req: AuthenticatedRequest, res: any) => {
  try {
    const { name, description, isAIPrompt, remasterWebsiteUrl, leadId } = req.body;
    if (!name) {
      return res.status(400).json({ error: 'Project name is required' });
    }

    const userId = req.userId as string;
    const project = await prisma.project.create({
      data: {
        name,
        description,
        members: {
          create: {
            userId,
            role: 'OWNER'
          }
        },
        pages: {
          create: {
            name: 'Home',
            slug: 'index',
            title: 'Home',
            isHomepage: true,
            html: `<div class="min-h-screen bg-slate-900 text-white flex flex-col justify-center items-center">
  <h1 class="text-4xl font-bold mb-4">Gerando site profissional...</h1>
  <p class="text-slate-400">Por favor, aguarde alguns instantes enquanto a IA constrói o mockup completo.</p>
</div>`,
            css: 'body { margin: 0; font-family: sans-serif; }',
            js: ''
          }
        }
      },
      include: {
        pages: true
      }
    });

    // Se um leadId foi fornecido, vincula o projeto diretamente ao lead no CRM
    if (leadId) {
      try {
        await prisma.$executeRawUnsafe(`
          UPDATE "Lead" SET "projectId" = $1 WHERE "id" = $2 AND "userId" = $3
        `, project.id, leadId, userId);
      } catch (leadLinkErr) {
        console.warn('Erro ao vincular lead ao projeto recém-criado:', leadLinkErr);
      }
    }

    // Busca configurações salvas no banco de dados do usuário como fallback prioritário
    let dbGeminiKey: string | undefined;
    let dbProxyUrl: string | undefined;
    let dbCustomModels: string[] | undefined;
    let dbCustomSkills: any[] | undefined;

    try {
      const userRows: any[] = await prisma.$queryRawUnsafe(`
        SELECT "geminiApiKey", "aiProxyUrl", "customAiModels", "customAiSkills" 
        FROM "User" 
        WHERE "id" = $1 LIMIT 1;
      `, userId);

      if (userRows && userRows.length > 0) {
        const userSettings = userRows[0];
        dbGeminiKey = userSettings.geminiApiKey || undefined;
        dbProxyUrl = userSettings.aiProxyUrl || undefined;
        if (userSettings.customAiModels && Array.isArray(userSettings.customAiModels)) {
          dbCustomModels = (userSettings.customAiModels as any[]).map(m => typeof m === 'string' ? m : m.id);
        }
        if (userSettings.customAiSkills && Array.isArray(userSettings.customAiSkills)) {
          dbCustomSkills = userSettings.customAiSkills as any[];
        }
      }
    } catch (e) {
      console.warn('Falha ao buscar configurações do usuário no banco:', e);
    }

    const clientGeminiKey = decodeHeader(req.headers['x-gemini-key'] || req.headers['X-Gemini-Key']) || dbGeminiKey || process.env.GEMINI_API_KEY;
    const clientProxyUrl = decodeHeader(req.headers['x-proxy-url'] || req.headers['X-Proxy-Url']) || dbProxyUrl || process.env.AI_PROXY_URL;
    let registeredModels: string[] | undefined = dbCustomModels;
    try {
      const rawModels = decodeHeader(req.headers['x-gemini-models'] || req.headers['X-Gemini-Models']);
      if (rawModels) registeredModels = JSON.parse(rawModels);
    } catch {}

    let customSkills: any[] | undefined = dbCustomSkills;
    try {
      const rawSkills = decodeHeader(req.headers['x-ai-skills'] || req.headers['X-Ai-Skills'] || req.headers['X-AI-Skills']);
      if (rawSkills) customSkills = JSON.parse(rawSkills);
    } catch {}

    // 1. Caso seja remasterização/melhoria de site existente (analisa páginas e subpáginas)
    if (remasterWebsiteUrl) {
      projectJobsQueue[project.id] = { status: 'pending' };
      processWebsiteRemasterJob(
        project.id,
        remasterWebsiteUrl,
        name,
        clientGeminiKey,
        registeredModels,
        clientProxyUrl,
        (status, attempt, total) => {
          projectJobsQueue[project.id] = {
            status: 'processing',
            currentModel: status,
            attempt,
            total
          };
        },
        customSkills
      ).then(() => {
        projectJobsQueue[project.id] = { status: 'completed' };
      }).catch((err) => {
        projectJobsQueue[project.id] = { status: 'failed', error: err.message };
      });
    } 
    // 2. Geração normal com IA a partir de prompt
    else if (isAIPrompt || description?.includes('Segmento:')) {
      const aiPromptMessage = `Gere um mockup completo e profissional de site para a empresa "${name}". Descrição detalhada do negócio: ${description}. Crie uma paleta elegante, seções funcionais (Hero, Serviços, Contato, FAQ) e um design moderno responsivo.`;
      
      // Enqueue job immediately on process memory thread
      projectJobsQueue[project.id] = { status: 'pending' };
      processAIProjectGeneration(project.id, aiPromptMessage, clientGeminiKey, undefined, registeredModels, clientProxyUrl, customSkills);
    }

    // Upload to FTP background
    try {
      await uploadProjectToFTP(project.name, project.pages);
    } catch (ftpErr) {
      console.error("Failed to upload newly created project to FTP:", ftpErr);
    }

    return res.status(201).json(project);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

// Get Project Details & Pages
router.get('/:id', async (req: AuthenticatedRequest, res: any) => {
  try {
    const id = req.params.id as string;
    const userId = req.userId as string;
    const project = await prisma.project.findFirst({
      where: {
        id,
        members: {
          some: {
            userId
          }
        }
      },
      include: {
        pages: true,
        assets: true
      }
    });

    if (!project) {
      return res.status(404).json({ error: 'Project not found' });
    }

    return res.json(project);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

// Update Project Info (Nome, Descrição, Status, Domínio)
router.put('/:id', async (req: AuthenticatedRequest, res: any) => {
  try {
    const id = req.params.id as string;
    const userId = req.userId as string;
    const { name, description, status, domain, favicon } = req.body;

    const membership = await prisma.projectMember.findFirst({
      where: {
        projectId: id,
        userId: userId
      }
    });

    if (!membership) {
      return res.status(403).json({ error: 'Você não tem permissão para editar este projeto' });
    }

    const updated = await prisma.project.update({
      where: { id },
      data: {
        ...(name !== undefined && { name: name.trim() }),
        ...(description !== undefined && { description: description?.trim() || null }),
        ...(status !== undefined && { status }),
        ...(domain !== undefined && { domain: domain?.trim() || null }),
        ...(favicon !== undefined && { favicon })
      },
      include: {
        pages: {
          select: { id: true, name: true, slug: true, isHomepage: true }
        }
      }
    });

    return res.json(updated);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

// Update Project Globals (Navbar, Footer HTML)
router.put('/:id/globals', async (req: AuthenticatedRequest, res: any) => {
  try {
    const id = req.params.id as string;
    const userId = req.userId as string;
    const { navbarHtml, footerHtml } = req.body;

    const membership = await prisma.projectMember.findFirst({
      where: {
        projectId: id,
        userId: userId
      }
    });

    if (!membership) {
      return res.status(403).json({ error: 'Você não tem permissão para editar este projeto' });
    }

    const updated = await prisma.project.update({
      where: { id },
      data: {
        ...(navbarHtml !== undefined && { navbarHtml }),
        ...(footerHtml !== undefined && { footerHtml })
      },
      include: {
        pages: true
      }
    });

    // FTP Upload on Save
    try {
      await uploadProjectToFTP(updated.name, updated.pages, updated.navbarHtml, updated.footerHtml);
    } catch (ftpErr) {
      console.error("Failed to upload project pages to FTP on globals update:", ftpErr);
    }

    return res.json(updated);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

// Delete Project
router.delete('/:id', async (req: AuthenticatedRequest, res: any) => {
  try {
    const id = req.params.id as string;
    const userId = req.userId as string;

    const membership = await prisma.projectMember.findFirst({
      where: {
        projectId: id,
        userId: userId,
        role: 'OWNER'
      }
    });

    if (!membership) {
      return res.status(403).json({ error: 'Only the project owner can delete this project' });
    }

    // Cancela jobs de IA ativos na fila para este projeto
    if (projectJobsQueue[id]) {
      delete projectJobsQueue[id];
    }

    // Deleta os arquivos locais e a pasta do projeto em public/uploads/projects/:id
    const projectUploadsDir = path.join(process.cwd(), 'public', 'uploads', 'projects', id);
    if (fs.existsSync(projectUploadsDir)) {
      try {
        fs.rmSync(projectUploadsDir, { recursive: true, force: true });
      } catch (err) {
        console.warn(`Erro ao excluir pasta de uploads do projeto ${id}:`, err);
      }
    }

    // Deleta os registros na tabela Media associados ao projeto
    try {
      await prisma.$executeRawUnsafe(`DELETE FROM "Media" WHERE "projectId" = $1`, id);
    } catch (dbErr) {
      console.warn(`Erro ao deletar registros de mídias do projeto ${id}:`, dbErr);
    }

    await prisma.project.delete({ where: { id } });
    return res.json({ message: 'Project deleted successfully' });
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

// Import Project from ZIP (Base64)
router.post('/import-zip', async (req: AuthenticatedRequest, res: any) => {
  try {
    const { name, description, zipBase64, targetProjectId } = req.body;
    const userId = req.userId as string;

    if (!zipBase64) {
      return res.status(400).json({ error: 'Arquivo ZIP em Base64 é obrigatório.' });
    }

    const JSZip = (await import('jszip')).default;
    const zipData = Buffer.from(zipBase64.replace(/^data:.*?;base64,/, ''), 'base64');
    const zip = await JSZip.loadAsync(zipData);

    const extractedPages: Array<{
      name: string;
      slug: string;
      title: string;
      isHomepage: boolean;
      html: string;
      css: string;
      js: string;
    }> = [];

    const files = Object.keys(zip.files);
    const htmlFiles = files.filter(f => !zip.files[f].dir && f.endsWith('.html') && !f.startsWith('__MACOSX/'));

    if (htmlFiles.length === 0) {
      return res.status(400).json({ error: 'Nenhum arquivo HTML encontrado no arquivo ZIP.' });
    }

    for (const filePath of htmlFiles) {
      const rawHtml = await zip.file(filePath)!.async('string');
      const basename = filePath.split('/').pop()!.replace(/\.html$/, '');
      const isHome = basename === 'index' || basename === 'home' || filePath === 'index.html';
      const slug = isHome ? 'index' : basename.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      const nameTitle = isHome ? 'Home' : basename.charAt(0).toUpperCase() + basename.slice(1);

      // Tenta extrair <title>
      const titleMatch = rawHtml.match(/<title[^>]*>([^<]+)<\/title>/i);
      const title = titleMatch ? titleMatch[1].trim() : nameTitle;

      // Extrai corpo ou <div id="canvas-root"> ou <body>
      let bodyHtml = rawHtml;
      const bodyMatch = rawHtml.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
      if (bodyMatch) {
        bodyHtml = bodyMatch[1].trim();
      }

      // Procura arquivo CSS correspondente no ZIP
      let cssContent = '';
      const possibleCssFiles = [`css/${slug}.css`, `${slug}.css`, `css/style.css`, `style.css`];
      for (const cssPath of possibleCssFiles) {
        const found = zip.file(cssPath);
        if (found) {
          cssContent = await found.async('string');
          break;
        }
      }

      // Procura arquivo JS correspondente no ZIP
      let jsContent = '';
      const possibleJsFiles = [`js/${slug}.js`, `${slug}.js`, `js/script.js`, `script.js`];
      for (const jsPath of possibleJsFiles) {
        const found = zip.file(jsPath);
        if (found) {
          jsContent = await found.async('string');
          break;
        }
      }

      extractedPages.push({
        name: nameTitle,
        slug,
        title,
        isHomepage: isHome,
        html: bodyHtml,
        css: cssContent,
        js: jsContent
      });
    }

    // Garante que exista pelo menos uma Home
    if (!extractedPages.some(p => p.isHomepage) && extractedPages.length > 0) {
      extractedPages[0].isHomepage = true;
      extractedPages[0].slug = 'index';
    }

    let finalProject: any;

    if (targetProjectId) {
      // Importar / Mesclar em projeto existente
      const existing = await prisma.project.findFirst({
        where: { id: targetProjectId, members: { some: { userId } } }
      });
      if (!existing) return res.status(404).json({ error: 'Projeto alvo não encontrado.' });

      for (const ep of extractedPages) {
        const existingPage = await prisma.page.findFirst({
          where: { projectId: targetProjectId, slug: ep.slug }
        });

        if (existingPage) {
          await prisma.page.update({
            where: { id: existingPage.id },
            data: {
              name: ep.name,
              title: ep.title,
              html: ep.html,
              css: ep.css || existingPage.css,
              js: ep.js || existingPage.js
            }
          });
        } else {
          await prisma.page.create({
            data: {
              projectId: targetProjectId,
              name: ep.name,
              slug: ep.slug,
              title: ep.title,
              isHomepage: ep.isHomepage,
              html: ep.html,
              css: ep.css,
              js: ep.js
            }
          });
        }
      }

      finalProject = await prisma.project.findUnique({
        where: { id: targetProjectId },
        include: { pages: true }
      });
    } else {
      // Criar novo projeto a partir do ZIP
      const projectName = name || 'Site Importado (ZIP)';
      finalProject = await prisma.project.create({
        data: {
          name: projectName,
          description: description || `Projeto importado via arquivo ZIP com ${extractedPages.length} página(s).`,
          members: {
            create: {
              userId,
              role: 'OWNER'
            }
          },
          pages: {
            create: extractedPages.map(p => ({
              name: p.name,
              slug: p.slug,
              title: p.title,
              isHomepage: p.isHomepage,
              html: p.html,
              css: p.css,
              js: p.js
            }))
          }
        },
        include: {
          pages: true
        }
      });
    }

    return res.status(201).json(finalProject);
  } catch (error: any) {
    console.error('Erro ao importar projeto ZIP:', error);
    return res.status(500).json({ error: error.message || 'Falha ao processar arquivo ZIP.' });
  }
});

export const projectRouter = router;
