import { Router } from 'express';
import { prisma } from '../db';
import { AuthenticatedRequest } from '../middleware/auth';
import { uploadProjectToFTP } from '../services/ftp';
import { generateAIResponse } from '../services/gemini';

const router = Router();

export const projectJobsQueue: Record<string, { 
  status: 'pending' | 'processing' | 'completed' | 'failed'; 
  currentModel?: string;
  attempt?: number;
  total?: number;
  error?: string;
}> = {};

// Background task worker method
async function processAIProjectGeneration(
  projectId: string, 
  prompt: string, 
  customApiKey?: string, 
  customModel?: string, 
  registeredModels?: string[],
  customProxyUrl?: string
) {
  projectJobsQueue[projectId] = { status: 'processing' };
  try {
    const page = await prisma.page.findFirst({
      where: { projectId, isHomepage: true }
    });

    if (!page) throw new Error("Homepage page not found in project");

    // Invoke Gemini with dynamic attempt updates and proxy
    const response = await generateAIResponse(
      prompt,
      { html: page.html, css: page.css, js: page.js },
      customApiKey,
      customModel,
      registeredModels,
      (model, attempt, total) => {
        projectJobsQueue[projectId] = {
          status: 'processing',
          currentModel: model,
          attempt,
          total
        };
      },
      customProxyUrl
    );

    // Save final generated code to database
    await prisma.page.update({
      where: { id: page.id },
      data: {
        html: response.html || page.html,
        css: response.css || page.css,
        js: response.js || page.js
      }
    });

    // Mirror to version snapshot
    await prisma.version.create({
      data: {
        name: "AI Initial Setup",
        description: `Autogenerated mockup: ${prompt}`,
        projectId,
        snapshot: {
          pages: [
            {
              id: page.id,
              name: page.name,
              slug: page.slug,
              html: response.html || page.html,
              css: response.css || page.css,
              js: response.js || page.js
            }
          ]
        }
      }
    });

    projectJobsQueue[projectId] = { status: 'completed' };
  } catch (err: any) {
    console.error("AI Generation job worker error for project " + projectId + ":", err);
    projectJobsQueue[projectId] = { status: 'failed', error: err.message };
  }
}

// Check job task status endpoint
router.get('/jobs/:projectId/status', async (req: AuthenticatedRequest, res: any) => {
  const projectId = req.params.projectId as string;
  const job = projectJobsQueue[projectId] || { status: 'completed' }; // fallback default to completed if no active job queue exists
  return res.json(job);
});

// List Projects
router.get('/', async (req: AuthenticatedRequest, res: any) => {
  try {
    const userId = req.userId as string;
    const projects = await prisma.project.findMany({
      where: {
        members: {
          some: {
            userId
          }
        }
      },
      include: {
        pages: {
          select: {
            id: true
          }
        }
      }
    });
    return res.json(projects);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

import { processWebsiteRemasterJob } from '../services/siteRemaster';

// Create Project
router.post('/', async (req: AuthenticatedRequest, res: any) => {
  try {
    const { name, description, isAIPrompt, remasterWebsiteUrl } = req.body;
    if (!name) {
      return res.status(400).json({ error: 'Project name is required' });
    }

    const userId = req.userId as string;
    const project = await prisma.project.create({
      data: {
        name,
        description,
        members: {
          create: {
            userId,
            role: 'OWNER'
          }
        },
        pages: {
          create: {
            name: 'Home',
            slug: 'index',
            title: 'Home',
            isHomepage: true,
            html: `<div class="min-h-screen bg-slate-900 text-white flex flex-col justify-center items-center">
  <h1 class="text-4xl font-bold mb-4">Gerando site profissional...</h1>
  <p class="text-slate-400">Por favor, aguarde alguns instantes enquanto a IA constrói o mockup completo.</p>
</div>`,
            css: 'body { margin: 0; font-family: sans-serif; }',
            js: ''
          }
        }
      },
      include: {
        pages: true
      }
    });

    const clientGeminiKey = (req.headers['x-gemini-key'] || req.headers['X-Gemini-Key']) as string || process.env.GEMINI_API_KEY;
    const clientProxyUrl = (req.headers['x-proxy-url'] || req.headers['X-Proxy-Url']) as string || process.env.AI_PROXY_URL;
    let registeredModels: string[] | undefined;
    try {
      const rawModels = (req.headers['x-gemini-models'] || req.headers['X-Gemini-Models']) as string;
      if (rawModels) registeredModels = JSON.parse(rawModels);
    } catch {}

    // 1. Caso seja remasterização/melhoria de site existente (analisa páginas e subpáginas)
    if (remasterWebsiteUrl) {
      projectJobsQueue[project.id] = { status: 'pending' };
      processWebsiteRemasterJob(
        project.id,
        remasterWebsiteUrl,
        name,
        clientGeminiKey,
        registeredModels,
        clientProxyUrl,
        (status, attempt, total) => {
          projectJobsQueue[project.id] = {
            status: 'processing',
            currentModel: status,
            attempt,
            total
          };
        }
      ).then(() => {
        projectJobsQueue[project.id] = { status: 'completed' };
      }).catch((err) => {
        projectJobsQueue[project.id] = { status: 'failed', error: err.message };
      });
    } 
    // 2. Geração normal com IA a partir de prompt
    else if (isAIPrompt || description?.includes('Segmento:')) {
      const aiPromptMessage = `Gere um mockup completo e profissional de site para a empresa "${name}". Descrição detalhada do negócio: ${description}. Crie uma paleta elegante, seções funcionais (Hero, Serviços, Contato, FAQ) e um design moderno responsivo.`;
      
      // Enqueue job immediately on process memory thread
      projectJobsQueue[project.id] = { status: 'pending' };
      processAIProjectGeneration(project.id, aiPromptMessage, clientGeminiKey, undefined, registeredModels, clientProxyUrl);
    }

    // Upload to FTP background
    try {
      await uploadProjectToFTP(project.name, project.pages);
    } catch (ftpErr) {
      console.error("Failed to upload newly created project to FTP:", ftpErr);
    }

    return res.status(201).json(project);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

// Get Project Details & Pages
router.get('/:id', async (req: AuthenticatedRequest, res: any) => {
  try {
    const id = req.params.id as string;
    const userId = req.userId as string;
    const project = await prisma.project.findFirst({
      where: {
        id,
        members: {
          some: {
            userId
          }
        }
      },
      include: {
        pages: true,
        assets: true
      }
    });

    if (!project) {
      return res.status(404).json({ error: 'Project not found' });
    }

    return res.json(project);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

import { stopNgrokPreview } from '../services/ngrokService';

// Delete Project
router.delete('/:id', async (req: AuthenticatedRequest, res: any) => {
  try {
    const id = req.params.id as string;
    const userId = req.userId as string;

    const membership = await prisma.projectMember.findFirst({
      where: {
        projectId: id,
        userId: userId,
        role: 'OWNER'
      }
    });

    if (!membership) {
      return res.status(403).json({ error: 'Only the project owner can delete this project' });
    }

    // 1. Derruba o túnel Ngrok do projeto se estiver ativo
    try {
      await stopNgrokPreview(id);
    } catch (ngErr) {
      console.warn(`Erro ao derrubar túnel Ngrok na exclusão do projeto ${id}:`, ngErr);
    }

    // 2. Cancela jobs de IA ativos na fila para este projeto
    if (projectJobsQueue[id]) {
      delete projectJobsQueue[id];
    }

    await prisma.project.delete({ where: { id } });
    return res.json({ message: 'Project deleted successfully' });
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

export const projectRouter = router;
